### PR TITLE
#11 cmdline opts to select processor and output a PLY file

### PR DESCRIPTION
**Pull request by ahundt**
#11

### CODE REVIEW

**Comment by giacomodabisias** [comment]
Hi,wouldn't it be better to simply have a button pressed to store a cloud with an increasing index?

**Comment by giacomodabisias** [comment]
I would just include the third commit since the others are not really fundemantal but optional and leave the others on your brench

**Comment by ahundt** [comment]
Thanks for considering merging my patches!

Ideally I'd very much appreciate if you could merge the full thing for the following reasons: 
- on certain platforms not all processor modes actually work, the current default in particular is broken on OS X
- Saving a .ply is an easy way to test your library!
- You can show the .ply results to others when you don't have the kinect sitting in front of you! (that's why I made these changes)
- I was careful to ensure the patch doesn't add new dependencies, it only adds pcl and standard library functions.
- I won't have to deal with merge conflicts if you make a few upstream changes (this one is just for me, I guess). 

You can get "button press" like functionality via command line tricks (i.e. no code changes needed!):

```
./Kinect2Grabber myfilename`date +"%Y-%m-%dT%H:%M:%SZ"`.ply
```
Just run the command every time you want to save a new file!

Button presses can be a bit painful to deal with in C++ in the `main.cpp` on command line in a way that works for more than one OS... Nonetheless, I could look into adding that if you'd be happier merging a version with that feature. 

Thanks again for taking a look at my patch!

**Comment by giacomodabisias** [comment]
Hi ,
I can marge it if you could change the button press to a simple keyboard button press (like s).This can be done easily using the visualizer which can have a listener 

boost::signals2::connection 	registerKeyboardCallback (boost::function< void(const pcl::visualization::KeyboardEvent &)> cb)

from http://docs.pointclouds.org/1.7.0/classpcl_1_1visualization_1_1_p_c_l_visualizer.html

Also it should be possible to press it many times saving every time a new cloud which should contain the date in the name (use std::chrone if possible).
I could make it by myself, but right now I am away from my lab and I don't have a kinect2 to check if everything is working .)

**Comment by giacomodabisias** [comment]
I will start merging just a part of it and then whenever you want we can insert the rest

**Comment by ahundt** [comment]
@giacomodabisias I've made quite a few important changes now. 
- Now builds without OpenCL. 
- There is an option to un-mirror the data. 
- Removed the cmake/FindFreenect2.cmake because freenect itself provides freenect2Config.cmake
- merged your changes as well as possible

I know this doesn't have the keypress thing, but I think it is worth considering. Also some of this, especially mirroring, is probably worth putting directly into [your PCL changes](https://github.com/PointCloudLibrary/pcl/pull/1410)

**Comment by giacomodabisias** [comment]
Looks good,
I  just changed some small things after merging. I will fix the button press, remove the normals in the example since this is just a grabber since I want it to have a clean example for just grabbing the cloud. 
For the rest thanks :)

**Comment by ahundt** [comment]
sure, thanks for merging :-)

**Comment by ahundt** [comment]
your code has proven super useful to me so I'm happy I can contribute something back

**Comment by giacomodabisias** [comment]
You're welcome

**Pull request merged**
