### PR TITLE
Inherit pcl::Grabber. Migrate to C++03.

### PR DESCRIPTION
**Pull request by ttikkanen**
Make class K2G a subclass of pcl::Grabber.

Remove C++11 specific code and -std=c++11 flag.

Clean formatting & spelling errors.

**The fork compiles but is NOT tested.** Function getColor() might not be as optimal as before, but good enough. I don't know how efficiently return local variable data in C++03.

**TODO**: make a callback register function.

### CODE REVIEW

**Comment by giacomodabisias** [comment]
Hi ttikkanen,
I also wanted to create directly the grabber for pcl.
I would prefer to leave this separate and maybe create the pcl grabber separately; if you want we can work together on it.

**Comment by ttikkanen** [comment]
Hi Giacomo,

I thought just to create a pull request in case you are interested, but of
course you can decide what you want to do with it. One option is to make a
separate branch.

I will only use my fork anyway. I'll try to get the callback working next.

Thanks for the fast reply!

2015-10-20 12:04 GMT+03:00 Giacomo Dabisias <notifications@github.com>:

**Comment by giacomodabisias** [comment]
Sure,
make a separate branch and make a pull request ;)

2015-10-20 11:16 GMT+02:00 Tommi <notifications@github.com>:

> Hi Giacomo,
>
> I thought just to create a pull request in case you are interested, but of
> course you can decide what you want to do with it. One option is to make a
> separate branch.
>
> I will only use my fork anyway. I'll try to get the callback working next.
>
> Thanks for the fast reply!
>
> 2015-10-20 12:04 GMT+03:00 Giacomo Dabisias <notifications@github.com>:
>
> > Hi ttikkanen,
> > I also wanted to create directly the grabber for pcl.
> > I would prefer to leave this separate and maybe create the pcl grabber
> > separately; if you want we can work together on it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/giacomodabisias/libfreenect2pclgrabber/pull/8#issuecomment-149485547
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/giacomodabisias/libfreenect2pclgrabber/pull/8#issuecomment-149488456>
> .
>



-- 
G. Dabisias, PhD Student
PERCRO, (Laboratory of Perceptual Robotics)
Scuola Superiore Sant'Anna
via Luigi Alamanni 13D, San Giuliano Terme 56010 (PI), Italy
mob.: +39 3480839095

**Comment by ttikkanen** [comment]
Moved to https://github.com/giacomodabisias/libfreenect2pclgrabber/pull/9

**Pull request closed without merging**
